enyo.depends(
	"$lib/layout",
	//"$lib/onyx/source",	// To theme Onyx using Theme.less, change this line to $lib/onyx/source,
	"$lib/onyx",	// To theme Onyx using Theme.less, change this line to $lib/onyx/source,
	//"Theme.less",	// uncomment this line, and follow the steps described in Theme.less
	"App.css",
	"App.js",
	"CampaignBuilder.js",
	"ComplexSensr.js",
	"CreateMap.js",
	"CSenseCreateCampaign.js",
	"CSenseLoginRegister.js",
	"CSenseShowCampaigns.js",
	"CSenseTaskDetail.js",
	"Data.js",
	"EditableListItem.js",
	"GrouplensBrand.js",
	"LocalStorage.js",
	"QuestionBuilder.js",
	"QuestionDrawer.js",
	"rok.geolocation.js",
	"SaveTitle.js",
	"SaveTitledInput.js",
	"SensorChooser.js",
	"ShowMap.js",
	"StepBuilder.js",
	"TaskBuilder.js",
	"Title.js",
	"TitledDrawer.js",
	"TitledInput.js",
	"TitledTextArea.js"
);
